name: Docker Build & Deploy

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  build_and_push:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: puzzlepop2:ai-server

  deploy:
    runs-on: ubuntu-22.04-arm
    needs: build_and_push

    steps:
      - name: 가상머신 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su - <<EOF
            cd /root/puzzlepop2
            docker stop ai-server || true
            docker rm ai-server || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:ai-server || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:ai-server
            docker run -d --name ai-server -p 8100:8100 ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:ai-server
            docker image prune -f
            EOF
